<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<AssemblyName>Piper.Test</AssemblyName>
		<RootNamespace>@(AssemblyName)</RootNamespace>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.Playwright.MSTest.v4" />
		<PackageReference Include="Verify.ImageHash" />
		<PackageReference Include="Verify.Playwright" />
	</ItemGroup>
</Project>
